# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='mainApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_account',
            field=models.CharField(default='no email', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gmail_id',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
