# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_userprofile_gmail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.TextField(null=True),
        ),
    ]
