# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20170529_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
