# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_thread_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
