# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20170529_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_id',
            field=models.TextField(null=True),
        ),
    ]
