# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_userprofile_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
