# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_userprofile_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
